import type { IngredientDefinition } from "./catalog-types.js";

function ingredient(
  id: string,
  label: string,
  aliases: string[],
  category: string,
  unit: string,
  quantity = 1,
): IngredientDefinition {
  return {
    id,
    label,
    aliases,
    shoppingDefaults: {
      name: label,
      category,
      quantity,
      unit,
    },
  };
}

export const ingredientRegistry: IngredientDefinition[] = [
  ingredient("nasi", "Beras", ["beras", "nasi", "rice"], "Makanan", "kg"),
  ingredient("mi", "Mi", ["mi", "mie", "noodle", "noodles"], "Makanan", "bungkus"),
  ingredient("bihun", "Bihun", ["bihun", "rice vermicelli"], "Makanan", "bungkus"),
  ingredient("spaghetti", "Spaghetti", ["spaghetti", "pasta spaghetti"], "Makanan", "bungkus"),
  ingredient("makaroni", "Makaroni", ["makaroni", "macaroni"], "Makanan", "bungkus"),
  ingredient("roti", "Roti Tawar", ["roti", "roti tawar", "bread", "toast bread"], "Makanan", "bungkus"),
  ingredient("tortilla", "Tortilla", ["tortilla", "wrap"], "Makanan", "bungkus"),
  ingredient("tepung", "Tepung Terigu", ["tepung", "tepung terigu", "flour"], "Makanan", "kg"),
  ingredient("telur", "Telur Ayam", ["telur", "telur ayam", "telor", "egg", "eggs"], "Makanan", "pcs"),
  ingredient("ayam", "Ayam", ["ayam", "daging ayam", "ayam fillet", "chicken"], "Makanan", "kg"),
  ingredient("sapi", "Daging Sapi", ["daging sapi", "sapi", "beef"], "Makanan", "kg"),
  ingredient("udang", "Udang", ["udang", "shrimp", "prawn"], "Makanan", "kg"),
  ingredient("ikan", "Ikan", ["ikan", "fish"], "Makanan", "kg"),
  ingredient("tuna_kaleng", "Tuna Kaleng", ["tuna", "tuna kaleng", "canned tuna"], "Makanan", "kaleng"),
  ingredient("sarden_kaleng", "Sarden Kaleng", ["sarden", "sarden kaleng", "canned sardines"], "Makanan", "kaleng"),
  ingredient("sosis", "Sosis", ["sosis", "sausage", "sausages"], "Makanan", "bungkus"),
  ingredient("bakso", "Bakso", ["bakso", "meatball", "meatballs"], "Makanan", "bungkus"),
  ingredient("tahu", "Tahu", ["tahu", "tofu"], "Makanan", "pcs"),
  ingredient("tempe", "Tempe", ["tempe", "tempeh"], "Makanan", "pcs"),
  ingredient("kentang", "Kentang", ["kentang", "potato", "potatoes"], "Makanan", "kg"),
  ingredient("wortel", "Wortel", ["wortel", "carrot", "carrots"], "Makanan", "kg"),
  ingredient("kol", "Kol", ["kol", "kubis", "cabbage"], "Makanan", "kg"),
  ingredient("sawi", "Sawi", ["sawi", "pakcoy", "bok choy", "bokchoy"], "Makanan", "ikat"),
  ingredient("bayam", "Bayam", ["bayam", "spinach"], "Makanan", "ikat"),
  ingredient("buncis", "Buncis", ["buncis", "green beans"], "Makanan", "kg"),
  ingredient("tauge", "Tauge", ["tauge", "bean sprout", "bean sprouts"], "Makanan", "bungkus"),
  ingredient("timun", "Timun", ["timun", "mentimun", "cucumber"], "Makanan", "kg"),
  ingredient("selada", "Selada", ["selada", "lettuce"], "Makanan", "ikat"),
  ingredient("jamur", "Jamur", ["jamur", "mushroom", "mushrooms"], "Makanan", "bungkus"),
  ingredient("jagung", "Jagung", ["jagung", "corn"], "Makanan", "pcs"),
  ingredient("tomat", "Tomat", ["tomat", "tomato", "tomatoes"], "Makanan", "kg"),
  ingredient("bawang_merah", "Bawang Merah", ["bawang merah", "shallot", "shallots"], "Bumbu Dapur", "kg"),
  ingredient("bawang_putih", "Bawang Putih", ["bawang putih", "garlic"], "Bumbu Dapur", "kg"),
  ingredient("daun_bawang", "Daun Bawang", ["daun bawang", "scallion", "green onion"], "Bumbu Dapur", "ikat"),
  ingredient("seledri", "Seledri", ["seledri", "celery"], "Bumbu Dapur", "ikat"),
  ingredient("cabai", "Cabai Merah", ["cabai", "cabai merah", "chili", "red chili"], "Bumbu Dapur", "kg"),
  ingredient("cabai_rawit", "Cabai Rawit", ["cabai rawit", "rawit", "bird chili"], "Bumbu Dapur", "kg"),
  ingredient("jahe", "Jahe", ["jahe", "ginger"], "Bumbu Dapur", "kg"),
  ingredient("kunyit", "Kunyit", ["kunyit", "turmeric"], "Bumbu Dapur", "kg"),
  ingredient("ketumbar", "Ketumbar", ["ketumbar", "coriander"], "Bumbu Dapur", "bungkus"),
  ingredient("lengkuas", "Lengkuas", ["lengkuas", "galangal"], "Bumbu Dapur", "kg"),
  ingredient("serai", "Serai", ["serai", "lemongrass"], "Bumbu Dapur", "ikat"),
  ingredient("daun_jeruk", "Daun Jeruk", ["daun jeruk", "kaffir lime leaf"], "Bumbu Dapur", "ikat"),
  ingredient("jeruk_nipis", "Jeruk Nipis", ["jeruk nipis", "lime"], "Bumbu Dapur", "pcs"),
  ingredient("asam", "Asam Jawa", ["asam", "asam jawa", "tamarind"], "Bumbu Dapur", "bungkus"),
  ingredient("santan", "Santan", ["santan", "coconut milk"], "Makanan", "liter"),
  ingredient("susu", "Susu", ["susu", "milk"], "Minuman", "liter"),
  ingredient("keju", "Keju", ["keju", "cheese"], "Makanan", "bungkus"),
  ingredient("mentega", "Mentega", ["mentega", "butter", "margarine"], "Bumbu Dapur", "bungkus"),
  ingredient("minyak", "Minyak Goreng", ["minyak", "minyak goreng", "cooking oil"], "Bumbu Dapur", "liter"),
  ingredient("garam", "Garam", ["garam", "salt"], "Bumbu Dapur", "bungkus"),
  ingredient("gula", "Gula", ["gula", "sugar"], "Bumbu Dapur", "kg"),
  ingredient("lada", "Lada", ["lada", "merica", "pepper"], "Bumbu Dapur", "bungkus"),
  ingredient("kaldu", "Kaldu Bubuk", ["kaldu", "kaldu bubuk", "broth powder", "stock powder"], "Bumbu Dapur", "bungkus"),
  ingredient("kecap_manis", "Kecap Manis", ["kecap manis", "sweet soy sauce"], "Bumbu Dapur", "botol"),
  ingredient("kecap_asin", "Kecap Asin", ["kecap asin", "soy sauce"], "Bumbu Dapur", "botol"),
  ingredient("saus_tiram", "Saus Tiram", ["saus tiram", "oyster sauce"], "Bumbu Dapur", "botol"),
  ingredient("saus_tomat", "Saus Tomat", ["saus tomat", "tomato sauce", "ketchup"], "Bumbu Dapur", "botol"),
  ingredient("saus_cabai", "Saus Cabai", ["saus cabai", "chili sauce"], "Bumbu Dapur", "botol"),
  ingredient("mayones", "Mayones", ["mayones", "mayonnaise"], "Bumbu Dapur", "botol"),
  ingredient("sambal", "Sambal", ["sambal"], "Bumbu Dapur", "botol"),
  ingredient("kacang_tanah", "Kacang Tanah", ["kacang tanah", "peanut", "peanuts"], "Makanan", "kg"),
  ingredient("bubuk_kari", "Bubuk Kari", ["bubuk kari", "kari bubuk", "curry powder"], "Bumbu Dapur", "bungkus"),
  ingredient("tepung_roti", "Tepung Roti", ["tepung roti", "bread crumbs", "breadcrumbs"], "Makanan", "bungkus"),
  ingredient("selai_cokelat", "Selai Cokelat", ["selai cokelat", "chocolate spread"], "Makanan", "botol"),
  ingredient("pisang", "Pisang", ["pisang", "banana"], "Makanan", "sisir"),
  ingredient("apel", "Apel", ["apel", "apple"], "Makanan", "kg"),
  ingredient("oat", "Oat", ["oat", "oats", "rolled oats"], "Makanan", "bungkus"),
];
