import type { RecipeDefinition } from "./catalog-types.js";

type RecipeTuple = [string, string, string[], string[], string[]];

function recipe(config: Omit<RecipeDefinition, "cuisine">): RecipeDefinition {
  return {
    ...config,
    cuisine: "indonesia",
    tags: [...new Set(config.tags)],
    requiredIngredients: [...new Set(config.requiredIngredients)],
    optionalIngredients: [...new Set(config.optionalIngredients)],
  };
}

const nasiGorengRecipes = [
  {
    id: "indo-nasi-goreng-telur",
    name: "Nasi Goreng Telur",
    summary: "Nasi goreng rumahan yang cepat untuk sarapan atau makan malam.",
    tags: ["sarapan", "makan-malam", "goreng", "simple"],
    requiredIngredients: ["nasi", "telur", "kecap_manis"],
    optionalIngredients: ["bawang_putih", "daun_bawang", "cabai", "minyak"],
  },
  {
    id: "indo-nasi-goreng-ayam",
    name: "Nasi Goreng Ayam",
    summary: "Nasi goreng gurih dengan ayam yang cocok untuk stok lauk sisa.",
    tags: ["makan-siang", "makan-malam", "goreng"],
    requiredIngredients: ["nasi", "ayam", "kecap_manis"],
    optionalIngredients: ["bawang_putih", "cabai", "daun_bawang", "minyak"],
  },
  {
    id: "indo-nasi-goreng-sosis",
    name: "Nasi Goreng Sosis",
    summary: "Varian praktis dengan sosis dan kecap manis.",
    tags: ["sarapan", "goreng", "simple"],
    requiredIngredients: ["nasi", "sosis", "kecap_manis"],
    optionalIngredients: ["telur", "bawang_putih", "cabai", "minyak"],
  },
  {
    id: "indo-nasi-goreng-bakso",
    name: "Nasi Goreng Bakso",
    summary: "Nasi goreng favorit keluarga dengan potongan bakso.",
    tags: ["makan-siang", "makan-malam", "goreng"],
    requiredIngredients: ["nasi", "bakso", "kecap_manis"],
    optionalIngredients: ["telur", "bawang_putih", "cabai", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-udang",
    name: "Nasi Goreng Udang",
    summary: "Nasi goreng seafood sederhana dengan rasa gurih segar.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["nasi", "udang", "kecap_asin"],
    optionalIngredients: ["bawang_putih", "cabai", "daun_bawang", "minyak"],
  },
  {
    id: "indo-nasi-goreng-ikan",
    name: "Nasi Goreng Ikan",
    summary: "Cara cepat mengolah ikan matang atau fillet menjadi menu utama.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["nasi", "ikan", "kecap_manis"],
    optionalIngredients: ["bawang_putih", "cabai", "daun_bawang", "minyak"],
  },
  {
    id: "indo-nasi-goreng-tuna",
    name: "Nasi Goreng Tuna",
    summary: "Nasi goreng berbasis tuna kaleng untuk stok pantry yang praktis.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["nasi", "tuna_kaleng", "kecap_manis"],
    optionalIngredients: ["bawang_putih", "cabai", "daun_bawang", "minyak"],
  },
  {
    id: "indo-nasi-goreng-sarden",
    name: "Nasi Goreng Sarden",
    summary: "Versi cepat dengan sarden kaleng yang kaya rasa.",
    tags: ["makan-malam", "goreng", "simple"],
    requiredIngredients: ["nasi", "sarden_kaleng", "saus_tomat"],
    optionalIngredients: ["cabai", "bawang_putih", "daun_bawang", "minyak"],
  },
  {
    id: "indo-nasi-goreng-kampung",
    name: "Nasi Goreng Kampung",
    summary: "Nasi goreng klasik dengan telur dan cabai rawit.",
    tags: ["makan-malam", "goreng", "pedas"],
    requiredIngredients: ["nasi", "telur", "cabai_rawit"],
    optionalIngredients: ["bawang_putih", "kecap_manis", "minyak", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-jawa",
    name: "Nasi Goreng Jawa",
    summary: "Nasi goreng bumbu sederhana dengan rasa manis gurih khas rumahan.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["nasi", "telur", "kecap_manis"],
    optionalIngredients: ["kol", "cabai", "bawang_putih", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-pedas",
    name: "Nasi Goreng Pedas",
    summary: "Pilihan nasi goreng cabai untuk pencinta rasa pedas.",
    tags: ["makan-malam", "goreng", "pedas"],
    requiredIngredients: ["nasi", "cabai", "kecap_manis"],
    optionalIngredients: ["telur", "bawang_putih", "daun_bawang", "saus_cabai"],
  },
  {
    id: "indo-nasi-goreng-mentega",
    name: "Nasi Goreng Mentega",
    summary: "Nasi goreng ringan dengan aroma mentega yang nyaman.",
    tags: ["sarapan", "makan-siang", "goreng", "simple"],
    requiredIngredients: ["nasi", "mentega", "telur"],
    optionalIngredients: ["bawang_putih", "lada", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-jamur",
    name: "Nasi Goreng Jamur",
    summary: "Nasi goreng gurih berbasis jamur untuk menu tanpa daging.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["nasi", "jamur", "kecap_asin"],
    optionalIngredients: ["bawang_putih", "daun_bawang", "telur", "minyak"],
  },
  {
    id: "indo-nasi-goreng-jagung",
    name: "Nasi Goreng Jagung",
    summary: "Nasi goreng sederhana dengan manis alami dari jagung.",
    tags: ["sarapan", "goreng", "simple"],
    requiredIngredients: ["nasi", "jagung", "telur"],
    optionalIngredients: ["bawang_putih", "kecap_manis", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-kol",
    name: "Nasi Goreng Kol",
    summary: "Menu hemat dengan kol yang tetap gurih dan mengenyangkan.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["nasi", "kol", "telur"],
    optionalIngredients: ["bawang_putih", "kecap_manis", "cabai", "minyak"],
  },
  {
    id: "indo-nasi-goreng-tauge",
    name: "Nasi Goreng Tauge",
    summary: "Nasi goreng sayur sederhana dengan tekstur renyah.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["nasi", "tauge", "telur"],
    optionalIngredients: ["bawang_putih", "kecap_manis", "cabai", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-teri-gaya",
    name: "Nasi Goreng Gaya Teri",
    summary: "Versi gurih asin yang cocok memakai lauk ikan yang tersedia.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["nasi", "ikan", "kecap_asin"],
    optionalIngredients: ["cabai_rawit", "bawang_putih", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-keju",
    name: "Nasi Goreng Keju",
    summary: "Nasi goreng fusion sederhana untuk stok keju di kulkas.",
    tags: ["sarapan", "goreng", "simple"],
    requiredIngredients: ["nasi", "keju", "telur"],
    optionalIngredients: ["mentega", "lada", "daun_bawang"],
  },
  {
    id: "indo-nasi-goreng-saus-tiram",
    name: "Nasi Goreng Saus Tiram",
    summary: "Nasi goreng gurih dengan profil rasa ala Chinese-style rumahan.",
    tags: ["makan-siang", "goreng"],
    requiredIngredients: ["nasi", "saus_tiram", "ayam"],
    optionalIngredients: ["bawang_putih", "daun_bawang", "cabai", "minyak"],
  },
  {
    id: "indo-nasi-goreng-spesial-rumah",
    name: "Nasi Goreng Spesial Rumah",
    summary: "Gabungan telur, ayam, dan sayur untuk menu lengkap cepat saji.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["nasi", "telur", "ayam", "kecap_manis"],
    optionalIngredients: ["kol", "cabai", "bawang_putih", "daun_bawang"],
  },
].map(recipe);

const noodleRecipes = [
  {
    id: "indo-mi-goreng-telur",
    name: "Mi Goreng Telur",
    summary: "Mi goreng sederhana yang mudah dibuat dari stok dasar pantry.",
    tags: ["sarapan", "makan-malam", "goreng", "simple"],
    requiredIngredients: ["mi", "telur", "kecap_manis"],
    optionalIngredients: ["bawang_putih", "cabai", "kol", "tauge"],
  },
  {
    id: "indo-mi-goreng-ayam",
    name: "Mi Goreng Ayam",
    summary: "Mi goreng gurih dengan ayam untuk menu satu panci.",
    tags: ["makan-siang", "makan-malam", "goreng"],
    requiredIngredients: ["mi", "ayam", "kecap_manis"],
    optionalIngredients: ["bawang_putih", "kol", "tauge", "cabai"],
  },
  {
    id: "indo-mi-goreng-sosis",
    name: "Mi Goreng Sosis",
    summary: "Pilihan cepat dengan sosis yang disukai keluarga.",
    tags: ["sarapan", "goreng", "simple"],
    requiredIngredients: ["mi", "sosis", "kecap_manis"],
    optionalIngredients: ["telur", "kol", "cabai", "bawang_putih"],
  },
  {
    id: "indo-mi-goreng-bakso",
    name: "Mi Goreng Bakso",
    summary: "Mi goreng gurih dengan bakso dan sayur sederhana.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["mi", "bakso", "kecap_manis"],
    optionalIngredients: ["tauge", "kol", "bawang_putih", "cabai"],
  },
  {
    id: "indo-mi-goreng-udang",
    name: "Mi Goreng Udang",
    summary: "Mi goreng seafood sederhana dengan rasa gurih asin.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["mi", "udang", "kecap_asin"],
    optionalIngredients: ["bawang_putih", "cabai", "daun_bawang", "kol"],
  },
  {
    id: "indo-mi-goreng-jawa",
    name: "Mi Goreng Jawa",
    summary: "Versi manis gurih dengan telur dan sayur dasar.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["mi", "telur", "kecap_manis"],
    optionalIngredients: ["kol", "cabai", "bawang_putih", "tauge"],
  },
  {
    id: "indo-mi-goreng-pedas",
    name: "Mi Goreng Pedas",
    summary: "Mi goreng simpel dengan sentuhan cabai yang menonjol.",
    tags: ["makan-malam", "goreng", "pedas"],
    requiredIngredients: ["mi", "cabai", "telur"],
    optionalIngredients: ["kecap_manis", "bawang_putih", "kol", "saus_cabai"],
  },
  {
    id: "indo-mi-goreng-jamur",
    name: "Mi Goreng Jamur",
    summary: "Mi goreng non-daging yang tetap gurih dan mengenyangkan.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["mi", "jamur", "kecap_asin"],
    optionalIngredients: ["bawang_putih", "kol", "daun_bawang", "telur"],
  },
  {
    id: "indo-mi-goreng-kol",
    name: "Mi Goreng Kol",
    summary: "Menu ekonomis dengan kol sebagai isi utama.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["mi", "kol", "telur"],
    optionalIngredients: ["kecap_manis", "bawang_putih", "cabai", "tauge"],
  },
  {
    id: "indo-mi-goreng-tauge",
    name: "Mi Goreng Tauge",
    summary: "Mi goreng segar dengan tekstur renyah dari tauge.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["mi", "tauge", "telur"],
    optionalIngredients: ["kecap_manis", "bawang_putih", "cabai", "daun_bawang"],
  },
  {
    id: "indo-bihun-goreng-ayam",
    name: "Bihun Goreng Ayam",
    summary: "Bihun goreng klasik dengan ayam dan kecap manis.",
    tags: ["makan-siang", "goreng"],
    requiredIngredients: ["bihun", "ayam", "kecap_manis"],
    optionalIngredients: ["wortel", "kol", "bawang_putih", "cabai"],
  },
  {
    id: "indo-bihun-goreng-telur",
    name: "Bihun Goreng Telur",
    summary: "Bihun goreng cepat untuk menu sarapan hangat.",
    tags: ["sarapan", "goreng", "simple"],
    requiredIngredients: ["bihun", "telur", "kecap_manis"],
    optionalIngredients: ["kol", "bawang_putih", "cabai", "daun_bawang"],
  },
  {
    id: "indo-bihun-goreng-sayur",
    name: "Bihun Goreng Sayur",
    summary: "Bihun dengan banyak sayur yang ringan tapi tetap kenyang.",
    tags: ["makan-siang", "goreng", "simple"],
    requiredIngredients: ["bihun", "kol", "wortel"],
    optionalIngredients: ["tauge", "bawang_putih", "kecap_manis", "daun_bawang"],
  },
  {
    id: "indo-bihun-goreng-udang",
    name: "Bihun Goreng Udang",
    summary: "Bihun seafood sederhana dengan rasa asin gurih.",
    tags: ["makan-malam", "goreng"],
    requiredIngredients: ["bihun", "udang", "kecap_asin"],
    optionalIngredients: ["wortel", "bawang_putih", "cabai", "daun_bawang"],
  },
  {
    id: "indo-bihun-kuah-ayam",
    name: "Bihun Kuah Ayam",
    summary: "Bihun berkuah ringan dengan ayam dan kaldu.",
    tags: ["makan-siang", "kuah", "simple"],
    requiredIngredients: ["bihun", "ayam", "kaldu"],
    optionalIngredients: ["wortel", "seledri", "daun_bawang", "bawang_putih"],
  },
  {
    id: "indo-bihun-kuah-bakso",
    name: "Bihun Kuah Bakso",
    summary: "Bihun kuah gurih yang cocok untuk stok bakso freezer.",
    tags: ["makan-siang", "kuah", "simple"],
    requiredIngredients: ["bihun", "bakso", "kaldu"],
    optionalIngredients: ["seledri", "daun_bawang", "bawang_putih", "lada"],
  },
  {
    id: "indo-mi-kuah-telur",
    name: "Mi Kuah Telur",
    summary: "Mi kuah sederhana dengan telur dan kaldu ringan.",
    tags: ["sarapan", "kuah", "simple"],
    requiredIngredients: ["mi", "telur", "kaldu"],
    optionalIngredients: ["bawang_putih", "daun_bawang", "kol", "lada"],
  },
  {
    id: "indo-mi-kuah-ayam",
    name: "Mi Kuah Ayam",
    summary: "Mi kuah gurih dengan ayam untuk menu hangat cepat.",
    tags: ["makan-siang", "kuah"],
    requiredIngredients: ["mi", "ayam", "kaldu"],
    optionalIngredients: ["daun_bawang", "seledri", "bawang_putih", "lada"],
  },
  {
    id: "indo-mi-kuah-sosis",
    name: "Mi Kuah Sosis",
    summary: "Mi kuah praktis dengan sosis dan sayur ringan.",
    tags: ["sarapan", "kuah", "simple"],
    requiredIngredients: ["mi", "sosis", "kaldu"],
    optionalIngredients: ["kol", "daun_bawang", "bawang_putih", "lada"],
  },
  {
    id: "indo-mi-kuah-jamur",
    name: "Mi Kuah Jamur",
    summary: "Mi kuah hangat dengan jamur untuk menu sederhana.",
    tags: ["makan-siang", "kuah", "simple"],
    requiredIngredients: ["mi", "jamur", "kaldu"],
    optionalIngredients: ["bawang_putih", "daun_bawang", "lada", "seledri"],
  },
].map(recipe);

const tumisRecipes = ([
  ["ayam-kol", "Tumis Ayam Kol", ["ayam", "kol"], ["bawang_putih", "saus_tiram", "cabai"], ["makan-siang", "goreng", "simple"]],
  ["ayam-sawi", "Tumis Ayam Sawi", ["ayam", "sawi"], ["bawang_putih", "saus_tiram", "cabai"], ["makan-siang", "goreng"]],
  ["ayam-jamur", "Tumis Ayam Jamur", ["ayam", "jamur"], ["bawang_putih", "saus_tiram", "lada"], ["makan-malam", "goreng"]],
  ["ayam-buncis", "Tumis Ayam Buncis", ["ayam", "buncis"], ["bawang_putih", "saus_tiram", "cabai"], ["makan-siang", "goreng"]],
  ["sapi-bawang", "Tumis Sapi Bawang", ["sapi", "bawang_putih"], ["kecap_asin", "lada", "cabai"], ["makan-malam", "goreng"]],
  ["sapi-jamur", "Tumis Sapi Jamur", ["sapi", "jamur"], ["bawang_putih", "saus_tiram", "lada"], ["makan-malam", "goreng"]],
  ["sapi-buncis", "Tumis Sapi Buncis", ["sapi", "buncis"], ["bawang_putih", "saus_tiram", "cabai"], ["makan-siang", "goreng"]],
  ["sapi-kol", "Tumis Sapi Kol", ["sapi", "kol"], ["bawang_putih", "kecap_asin", "lada"], ["makan-siang", "goreng"]],
  ["udang-jagung", "Tumis Udang Jagung", ["udang", "jagung"], ["bawang_putih", "mentega", "lada"], ["makan-malam", "goreng"]],
  ["udang-sawi", "Tumis Udang Sawi", ["udang", "sawi"], ["bawang_putih", "saus_tiram", "lada"], ["makan-malam", "goreng"]],
  ["udang-jamur", "Tumis Udang Jamur", ["udang", "jamur"], ["bawang_putih", "mentega", "lada"], ["makan-malam", "goreng"]],
  ["udang-buncis", "Tumis Udang Buncis", ["udang", "buncis"], ["bawang_putih", "saus_tiram", "cabai"], ["makan-siang", "goreng"]],
  ["tahu-kecap", "Tumis Tahu Kecap", ["tahu", "kecap_manis"], ["bawang_putih", "cabai", "daun_bawang"], ["makan-siang", "goreng", "simple"]],
  ["tahu-jamur", "Tumis Tahu Jamur", ["tahu", "jamur"], ["bawang_putih", "saus_tiram", "daun_bawang"], ["makan-siang", "goreng", "simple"]],
  ["tahu-tauge", "Tumis Tahu Tauge", ["tahu", "tauge"], ["bawang_putih", "cabai", "kecap_asin"], ["makan-siang", "goreng", "simple"]],
  ["tahu-kol", "Tumis Tahu Kol", ["tahu", "kol"], ["bawang_putih", "saus_tiram", "cabai"], ["makan-siang", "goreng", "simple"]],
  ["tempe-kecap", "Tumis Tempe Kecap", ["tempe", "kecap_manis"], ["bawang_putih", "cabai", "daun_bawang"], ["makan-siang", "goreng", "simple"]],
  ["tempe-kacang", "Tumis Tempe Kacang", ["tempe", "kacang_tanah"], ["cabai", "bawang_putih", "kecap_manis"], ["makan-siang", "goreng"]],
  ["tempe-buncis", "Tumis Tempe Buncis", ["tempe", "buncis"], ["bawang_putih", "cabai", "kecap_manis"], ["makan-siang", "goreng", "simple"]],
  ["tempe-jagung", "Tumis Tempe Jagung", ["tempe", "jagung"], ["bawang_putih", "cabai", "kecap_manis"], ["makan-siang", "goreng", "simple"]],
  ["jamur-kol", "Tumis Jamur Kol", ["jamur", "kol"], ["bawang_putih", "saus_tiram", "lada"], ["makan-siang", "goreng", "simple"]],
  ["jamur-sawi", "Tumis Jamur Sawi", ["jamur", "sawi"], ["bawang_putih", "saus_tiram", "lada"], ["makan-siang", "goreng", "simple"]],
  ["kol-tauge", "Tumis Kol Tauge", ["kol", "tauge"], ["bawang_putih", "cabai", "kecap_asin"], ["makan-siang", "goreng", "simple"]],
  ["buncis-wortel", "Tumis Buncis Wortel", ["buncis", "wortel"], ["bawang_putih", "saus_tiram", "lada"], ["makan-siang", "goreng", "simple"]],
] satisfies RecipeTuple[]).map(([slug, name, requiredIngredients, optionalIngredients, tags]) =>
  recipe({
    id: `indo-tumis-${slug}`,
    name,
    summary: `${name} adalah menu tumisan cepat untuk makan rumahan sehari-hari.`,
    tags: tags as string[],
    requiredIngredients: requiredIngredients as string[],
    optionalIngredients: optionalIngredients as string[],
  }),
);

const soupRecipes = ([
  ["sayur-bening-bayam", "Sayur Bening Bayam", ["bayam", "bawang_putih"], ["jagung", "wortel", "kaldu"], ["makan-siang", "kuah", "simple"]],
  ["sayur-bening-bayam-jagung", "Sayur Bening Bayam Jagung", ["bayam", "jagung"], ["bawang_putih", "kaldu", "wortel"], ["makan-siang", "kuah", "simple"]],
  ["sup-ayam-wortel", "Sup Ayam Wortel", ["ayam", "wortel", "kaldu"], ["kentang", "seledri", "bawang_putih"], ["makan-siang", "kuah"]],
  ["sup-ayam-kentang", "Sup Ayam Kentang", ["ayam", "kentang", "kaldu"], ["wortel", "seledri", "bawang_putih"], ["makan-siang", "kuah"]],
  ["sup-sapi-wortel", "Sup Sapi Wortel", ["sapi", "wortel", "kaldu"], ["kentang", "seledri", "lada"], ["makan-malam", "kuah"]],
  ["sup-sapi-kentang", "Sup Sapi Kentang", ["sapi", "kentang", "kaldu"], ["wortel", "seledri", "lada"], ["makan-malam", "kuah"]],
  ["sup-bakso-bihun", "Sup Bakso Bihun", ["bakso", "bihun", "kaldu"], ["seledri", "daun_bawang", "lada"], ["makan-siang", "kuah", "simple"]],
  ["sup-bakso-kentang", "Sup Bakso Kentang", ["bakso", "kentang", "kaldu"], ["wortel", "seledri", "lada"], ["makan-siang", "kuah"]],
  ["soto-ayam-sederhana", "Soto Ayam Sederhana", ["ayam", "kunyit", "serai"], ["daun_jeruk", "kol", "bihun"], ["makan-siang", "kuah"]],
  ["soto-ayam-bihun", "Soto Ayam Bihun", ["ayam", "bihun", "kunyit"], ["serai", "daun_jeruk", "kol"], ["makan-siang", "kuah"]],
  ["soto-ayam-kol", "Soto Ayam Kol", ["ayam", "kol", "kunyit"], ["serai", "daun_jeruk", "bihun"], ["makan-siang", "kuah"]],
  ["sayur-santan-labu-gaya", "Sayur Santan Jagung", ["santan", "jagung"], ["bawang_putih", "serai", "daun_jeruk"], ["makan-siang", "kuah"]],
  ["sayur-lodeh-kol", "Sayur Lodeh Kol", ["santan", "kol"], ["wortel", "buncis", "serai"], ["makan-siang", "kuah"]],
  ["sayur-lodeh-buncis", "Sayur Lodeh Buncis", ["santan", "buncis"], ["kol", "wortel", "serai"], ["makan-siang", "kuah"]],
  ["sayur-lodeh-terong-gaya", "Sayur Lodeh Tahu", ["santan", "tahu"], ["kol", "buncis", "serai"], ["makan-siang", "kuah"]],
  ["sayur-asam-sederhana", "Sayur Asam Sederhana", ["jagung", "kol"], ["kacang_tanah", "cabai", "asam"], ["makan-siang", "kuah", "simple"]],
  ["sup-jamur-ayam", "Sup Jamur Ayam", ["ayam", "jamur", "kaldu"], ["lada", "seledri", "bawang_putih"], ["makan-malam", "kuah"]],
  ["sup-jamur-sosis", "Sup Jamur Sosis", ["sosis", "jamur", "kaldu"], ["lada", "seledri", "bawang_putih"], ["makan-siang", "kuah", "simple"]],
  ["sop-tahu-bayam", "Sup Tahu Bayam", ["tahu", "bayam", "kaldu"], ["bawang_putih", "lada", "seledri"], ["makan-siang", "kuah", "simple"]],
  ["sup-udang-jagung", "Sup Udang Jagung", ["udang", "jagung", "kaldu"], ["seledri", "lada", "bawang_putih"], ["makan-malam", "kuah"]],
] satisfies RecipeTuple[]).map(([slug, name, requiredIngredients, optionalIngredients, tags]) =>
  recipe({
    id: `indo-kuah-${slug}`,
    name,
    summary: `${name} memberi pilihan menu berkuah hangat dengan bahan pantry rumahan.`,
    tags: tags as string[],
    requiredIngredients: requiredIngredients as string[],
    optionalIngredients: optionalIngredients as string[],
  }),
);

const laukRecipes = ([
  ["telur-dadar", "Telur Dadar", ["telur"], ["bawang_merah", "cabai", "daun_bawang"], ["sarapan", "goreng", "simple"]],
  ["telur-dadar-padang", "Telur Dadar Padang", ["telur", "daun_bawang"], ["cabai", "bawang_merah", "tepung"], ["makan-siang", "goreng"]],
  ["telur-balado", "Telur Balado", ["telur", "cabai"], ["bawang_merah", "saus_tomat", "gula"], ["makan-siang", "pedas"]],
  ["telur-kecap", "Telur Kecap", ["telur", "kecap_manis"], ["bawang_merah", "cabai", "lada"], ["makan-siang", "simple"]],
  ["telur-tomat", "Telur Tomat", ["telur", "tomat"], ["bawang_putih", "daun_bawang", "lada"], ["sarapan", "simple"]],
  ["telur-cabai-hijau-gaya", "Telur Cabai", ["telur", "cabai"], ["bawang_merah", "kecap_manis", "lada"], ["makan-siang", "pedas"]],
  ["ayam-goreng-kuning", "Ayam Goreng Kuning", ["ayam", "kunyit"], ["bawang_putih", "ketumbar", "minyak"], ["makan-siang", "goreng"]],
  ["ayam-kecap", "Ayam Kecap", ["ayam", "kecap_manis"], ["bawang_putih", "cabai", "tomat"], ["makan-malam", "simple"]],
  ["ayam-mentega", "Ayam Mentega", ["ayam", "mentega"], ["bawang_putih", "kecap_asin", "saus_tomat"], ["makan-malam"]],
  ["ayam-lada-hitam-gaya", "Ayam Lada", ["ayam", "lada"], ["bawang_putih", "kecap_asin", "mentega"], ["makan-malam"]],
  ["ayam-sambal", "Ayam Sambal", ["ayam", "sambal"], ["bawang_putih", "gula", "jeruk_nipis"], ["makan-siang", "pedas"]],
  ["ayam-bakar-teflon", "Ayam Bakar Teflon", ["ayam", "kecap_manis"], ["bawang_putih", "cabai", "mentega"], ["makan-malam"]],
  ["ayam-kari-sederhana", "Ayam Kari Sederhana", ["ayam", "bubuk_kari", "santan"], ["bawang_putih", "jahe", "serai"], ["makan-malam", "kuah"]],
  ["ayam-gulai-ringan", "Ayam Gulai Ringan", ["ayam", "santan", "kunyit"], ["serai", "lengkuas", "daun_jeruk"], ["makan-malam", "kuah"]],
  ["tahu-goreng-bumbu", "Tahu Goreng Bumbu", ["tahu"], ["bawang_putih", "garam", "lada"], ["makan-siang", "goreng", "simple"]],
  ["tahu-kecap", "Tahu Kecap", ["tahu", "kecap_manis"], ["bawang_putih", "cabai", "daun_bawang"], ["makan-siang", "simple"]],
  ["tahu-balado", "Tahu Balado", ["tahu", "cabai"], ["bawang_merah", "saus_tomat", "gula"], ["makan-siang", "pedas"]],
  ["tahu-sambal", "Tahu Sambal", ["tahu", "sambal"], ["bawang_putih", "jeruk_nipis", "gula"], ["makan-siang", "pedas"]],
  ["tahu-lada-garam-gaya", "Tahu Lada Garam", ["tahu", "lada"], ["bawang_putih", "daun_bawang", "tepung"], ["makan-siang", "goreng"]],
  ["tahu-kari", "Tahu Kari", ["tahu", "bubuk_kari", "santan"], ["bawang_putih", "jahe", "serai"], ["makan-siang", "kuah"]],
  ["tempe-goreng-bumbu", "Tempe Goreng Bumbu", ["tempe"], ["bawang_putih", "garam", "lada"], ["makan-siang", "goreng", "simple"]],
  ["tempe-orek", "Tempe Orek", ["tempe", "kecap_manis"], ["cabai", "bawang_putih", "gula"], ["makan-siang", "simple"]],
  ["tempe-balado", "Tempe Balado", ["tempe", "cabai"], ["bawang_merah", "saus_tomat", "gula"], ["makan-siang", "pedas"]],
  ["tempe-kecap-pedas", "Tempe Kecap Pedas", ["tempe", "kecap_manis", "cabai"], ["bawang_putih", "daun_bawang", "gula"], ["makan-siang", "pedas"]],
  ["tempe-sambal", "Tempe Sambal", ["tempe", "sambal"], ["bawang_putih", "gula", "jeruk_nipis"], ["makan-siang", "pedas"]],
  ["ikan-goreng-tepung", "Ikan Goreng Tepung", ["ikan", "tepung"], ["bawang_putih", "garam", "lada"], ["makan-siang", "goreng"]],
  ["ikan-kecap", "Ikan Kecap", ["ikan", "kecap_manis"], ["bawang_putih", "cabai", "tomat"], ["makan-malam", "simple"]],
  ["ikan-sambal", "Ikan Sambal", ["ikan", "sambal"], ["cabai", "jeruk_nipis", "gula"], ["makan-malam", "pedas"]],
] satisfies RecipeTuple[]).map(([slug, name, requiredIngredients, optionalIngredients, tags]) =>
  recipe({
    id: `indo-lauk-${slug}`,
    name,
    summary: `${name} adalah lauk rumahan yang mudah dimasak dari stok sehari-hari.`,
    tags: tags as string[],
    requiredIngredients: requiredIngredients as string[],
    optionalIngredients: optionalIngredients as string[],
  }),
);

const snackRecipes = ([
  ["omelet-sarapan", "Omelet Sarapan Gaya Rumahan", ["telur", "tomat"], ["keju", "daun_bawang", "lada"], ["sarapan", "simple"]],
  ["roti-telur", "Roti Telur", ["roti", "telur"], ["mentega", "lada", "keju"], ["sarapan", "simple"]],
  ["roti-keju", "Roti Panggang Keju", ["roti", "keju"], ["mentega", "mayones"], ["sarapan", "simple"]],
  ["roti-tuna", "Roti Tuna Mayo", ["roti", "tuna_kaleng", "mayones"], ["selada", "tomat"], ["sarapan", "simple"]],
  ["roti-sosis", "Roti Sosis Panggang", ["roti", "sosis"], ["saus_tomat", "keju", "mentega"], ["sarapan", "simple"]],
  ["roti-ayam-suvir-gaya", "Roti Ayam Suwir", ["roti", "ayam"], ["mayones", "selada", "tomat"], ["sarapan", "simple"]],
  ["bubur-ayam-sederhana", "Bubur Ayam Sederhana", ["nasi", "ayam"], ["daun_bawang", "kecap_manis", "kaldu"], ["sarapan", "kuah"]],
  ["bubur-telur", "Bubur Telur", ["nasi", "telur"], ["daun_bawang", "kaldu", "lada"], ["sarapan", "kuah", "simple"]],
  ["nasi-uduk-sederhana", "Nasi Uduk Sederhana", ["nasi", "santan"], ["daun_jeruk", "serai", "telur"], ["sarapan"]],
  ["nasi-kuning-ringan", "Nasi Kuning Ringan", ["nasi", "kunyit"], ["santan", "serai", "telur"], ["sarapan"]],
  ["martabak-telur-teflon", "Martabak Telur Teflon", ["telur", "tepung"], ["daun_bawang", "cabai", "ayam"], ["cemilan", "simple"]],
  ["perkedel-kentang", "Perkedel Kentang", ["kentang", "telur"], ["bawang_putih", "daun_bawang", "lada"], ["cemilan", "goreng"]],
  ["bakwan-sayur", "Bakwan Sayur", ["tepung", "kol", "wortel"], ["daun_bawang", "cabai", "bawang_putih"], ["cemilan", "goreng"]],
  ["bakwan-jagung", "Bakwan Jagung", ["tepung", "jagung"], ["daun_bawang", "bawang_putih", "cabai"], ["cemilan", "goreng"]],
  ["pisang-goreng", "Pisang Goreng", ["pisang", "tepung"], ["gula", "mentega"], ["cemilan", "goreng", "simple"]],
  ["roti-goreng-pisang", "Roti Gulung Pisang", ["roti", "pisang"], ["mentega", "gula", "keju"], ["cemilan", "simple"]],
  ["pancake-pisang-lokal", "Pancake Pisang Gaya Rumah", ["tepung", "pisang", "telur"], ["susu", "gula", "mentega"], ["sarapan", "cemilan"]],
  ["serabi-sederhana", "Serabi Sederhana", ["tepung", "santan"], ["gula", "pisang"], ["cemilan", "simple"]],
  ["omelet-jagung", "Omelet Jagung", ["telur", "jagung"], ["daun_bawang", "lada", "keju"], ["sarapan", "simple"]],
  ["omelet-jamur", "Omelet Jamur", ["telur", "jamur"], ["keju", "lada", "daun_bawang"], ["sarapan", "simple"]],
  ["omelet-sosis", "Omelet Sosis", ["telur", "sosis"], ["keju", "lada", "tomat"], ["sarapan", "simple"]],
  ["omelet-tahu", "Omelet Tahu", ["telur", "tahu"], ["daun_bawang", "lada", "cabai"], ["sarapan", "simple"]],
  ["sandwich-sambal-tuna-gaya", "Sandwich Tuna Sambal", ["roti", "tuna_kaleng"], ["sambal", "mayones", "selada"], ["sarapan", "simple"]],
  ["roti-cokelat-pisang", "Roti Cokelat Pisang", ["roti", "pisang", "selai_cokelat"], ["mentega"], ["cemilan", "simple"]],
  ["roti-keju-jagung", "Roti Keju Jagung", ["roti", "keju", "jagung"], ["mentega", "mayones"], ["cemilan", "simple"]],
  ["oat-pisang-susu", "Oat Pisang Susu", ["oat", "pisang", "susu"], ["gula", "apel"], ["sarapan", "simple"]],
  ["roti-apel-kayu-manis-gaya", "Roti Apel Manis", ["roti", "apel"], ["mentega", "gula"], ["cemilan", "simple"]],
  ["nasi-goreng-sarapan-cepat", "Nasi Goreng Sarapan Cepat", ["nasi", "telur"], ["kecap_manis", "daun_bawang", "cabai"], ["sarapan", "goreng", "simple"]],
] satisfies RecipeTuple[]).map(([slug, name, requiredIngredients, optionalIngredients, tags]) =>
  recipe({
    id: `indo-santai-${slug}`,
    name,
    summary: `${name} cocok untuk sarapan atau camilan saat bahan di rumah terbatas.`,
    tags: tags as string[],
    requiredIngredients: requiredIngredients as string[],
    optionalIngredients: optionalIngredients as string[],
  }),
);

export const indonesianRecipes: RecipeDefinition[] = [
  ...nasiGorengRecipes,
  ...noodleRecipes,
  ...tumisRecipes,
  ...soupRecipes,
  ...laukRecipes,
  ...snackRecipes,
];
