services:
  app:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:3001:3001"
